#数据库的配置
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8
    username: root
    password: garyhu
    driverClassName: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    initial-size: 10
#服务器设置，仅对java -jar 命令行启动的服务有效，如果直接项目以war放在tomcat中启动，此处不配置
server:
  port: 9000
  context-path: /
  session-timeout: 60
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    session:
      tracking-mode: COOKIE
  error:
    path: /error
student:
   message: 大三的学生
   id: 1000
   age: 20
   name: 张三    